services:
  - type: web
    name: course-enrollment-backend
    env: python
    branch: main
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT backend.app:app